import { forwardRef, type ReactNode, useMemo } from "react";
import { formatUsdc, type MarketplaceDeliverable } from "../api.ts";
import { strategyLabel } from "./utils.ts";
import { auditPaperTitle, isAuditDeliverable } from "./audit.ts";
import { billPaperTitle, isBillDeliverable } from "./bill.ts";
import { combineWorkflowResult } from "./combine.ts";
import { unwrapAgentPayload } from "./format.ts";

export const PaperDocument = forwardRef<
  HTMLElement,
  { job: MarketplaceDeliverable; children: ReactNode }
>(function PaperDocument({ job, children }, ref) {
  const date = new Date(job.at * 1000).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const strategy = strategyLabel(job.plan?.strategy);
  const isAudit = isAuditDeliverable(job);
  const isBill = !isAudit && isBillDeliverable(job);
  const payload = useMemo(() => {
    const done = job.steps.filter((s) => s.status === "done" && s.output != null);
    const merged = combineWorkflowResult(done);
    if (merged) return merged;
    const step = job.steps.find((s) => s.output != null);
    return step ? unwrapAgentPayload(step.output) : null;
  }, [job.steps]);
  const title = isAudit
    ? auditPaperTitle(job, payload)
    : isBill
      ? billPaperTitle(job, payload)
      : (job.brief ?? "Deliverable Report");
  const showAbstract =
    !isAudit && !isBill && job.plan?.reason && !/^single-agent task\.?$/i.test(job.plan.reason);
  const sheetClass = isAudit
    ? " library-paper-sheet--audit"
    : isBill
      ? " library-paper-sheet--bill"
      : "";

  return (
    <article className={`library-paper-sheet${sheetClass}`} ref={ref}>
      <header className="paper-masthead">
        <p className="paper-kicker">
          {isAudit ? "Butler Security Audit" : isBill ? "Butler Utility Quote" : "Butler Research Deliverable"}
        </p>
        <h1 className="paper-title">{title}</h1>
        <div className="paper-byline">
          <span>{strategy}</span>
          <span className="paper-byline-sep" aria-hidden>
            ·
          </span>
          <time dateTime={new Date(job.at * 1000).toISOString()}>{date}</time>
          <span className="paper-byline-sep" aria-hidden>
            ·
          </span>
          <span>${formatUsdc(job.totalUsdc)} USDC</span>
        </div>
        {showAbstract && (
          <div className="paper-abstract">
            <p className="paper-abstract-label">Abstract</p>
            <p className="paper-abstract-text">{job.plan!.reason}</p>
          </div>
        )}
      </header>

      <div className="paper-content">{children}</div>

      <footer className="paper-colophon">
        <p>Generated by Butler Agentic hub · Arc testnet · {date}</p>
      </footer>
    </article>
  );
});

/** Serializes the paper article DOM for print/PDF export. */
export function serializePaperForExport(root: HTMLElement): string {
  const clone = root.cloneNode(true) as HTMLElement;
  clone.querySelectorAll("[data-export-hide]").forEach((el) => el.remove());
  return clone.innerHTML;
}
